export default {
  "Action|Classless": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Action+Classless.png",
  "Action|Cleric": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Action+Cleric.png",
  "Action|Fighter": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Action+Fighter.png",
  "Action|Rogue": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Action+Rogue.png",
  "Action|Wizard": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Action+Wizard.png",
  "Character|Classless|Evil|Deverenian": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dev+E+Class+Half.png",
  "Character|Classless|Evil|Dwarf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dw+E+Class+Half.png",
  "Character|Classless|Evil|Elf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Elv+E+Class+Half.png",
  "Character|Classless|Evil|Free Kingdoms": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Freek+E+Class+Half.png",
  "Character|Classless|Evil|Mercenary": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Merc+E+Class+Half.png",
  "Character|Classless|Evil|Nothrog": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Ntg+E+Class+Half.png",
  "Character|Classless|Evil|The Chosen": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Cho+E+Class.png",
  "Character|Classless|Good|Deverenian": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dev+G+Class+Half.png",
  "Character|Classless|Good|Dwarf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dw+G+Class+Half.png",
  "Character|Classless|Good|Elf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Elv+G+Class+Half.png",
  "Character|Classless|Good|Free Kingdoms": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Freek+G+Class+Half.png",
  "Character|Classless|Good|Mercenary": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Merc+G+Class+Half.png",
  "Character|Classless|Good|Nothrog": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Ntg+G+Class+Half.png",
  "Character|Classless|Good|The Chosen": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Cho+G+Class.png",
  "Character|Cleric|Evil|Deverenian": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dev+E+Cleric+Half.png",
  "Character|Cleric|Evil|Dwarf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dw+E+Cleric+Half.png",
  "Character|Cleric|Evil|Elf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Elv+E+Cleric+Half.png",
  "Character|Cleric|Evil|Free Kingdoms": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Freek+E+Cleric+Half.png",
  "Character|Cleric|Evil|Mercenary": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Merc+E+Cleric+Half.png",
  "Character|Cleric|Evil|Nothrog": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Ntg+E+Cleric+Half.png",
  "Character|Cleric|Evil|The Chosen": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Cho+E+Cleric.png",
  "Character|Cleric|Good|Deverenian": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dev+G+Cleric+Half.png",
  "Character|Cleric|Good|Dwarf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dw+G+Cleric+Half.png",
  "Character|Cleric|Good|Elf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Elv+G+Cleric+Half.png",
  "Character|Cleric|Good|Free Kingdoms": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Freek+G+Cleric+Half.png",
  "Character|Cleric|Good|Mercenary": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Merc+G+Cleric+Half.png",
  "Character|Cleric|Good|Nothrog": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Ntg+G+Cleric+Half.png",
  "Character|Cleric|Good|The Chosen": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Cho+G+Cleric.png",
  "Character|Fighter|Evil|Deverenian": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dev+E+Fight+Half.png",
  "Character|Fighter|Evil|Dwarf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dw+E+Fight+Half.png",
  "Character|Fighter|Evil|Elf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Elv+E+Fight+Half.png",
  "Character|Fighter|Evil|Free Kingdoms": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Freek+E+Fight+Half.png",
  "Character|Fighter|Evil|Mercenary": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Merc+E+Fight+Half.png",
  "Character|Fighter|Evil|Nothrog": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Ntg+E+Fight+Half.png",
  "Character|Fighter|Evil|The Chosen": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Cho+E+Fight.png",
  "Character|Fighter|Good|Deverenian": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dev+G+Fight+Half.png",
  "Character|Fighter|Good|Dwarf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dw+G+Fight+Half.png",
  "Character|Fighter|Good|Elf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Elv+G+Fight+Half.png",
  "Character|Fighter|Good|Free Kingdoms": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Freek+G+Fight+Half.png",
  "Character|Fighter|Good|Mercenary": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Merc+G+Fight+Half.png",
  "Character|Fighter|Good|Nothrog": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Ntg+G+Fight+Half.png",
  "Character|Fighter|Good|The Chosen": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Cho+G+Fight.png",
  "Character|Rogue|Evil|Deverenian": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dev+E+Rogue+Half.png",
  "Character|Rogue|Evil|Dwarf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dw+E+Rogue+Half.png",
  "Character|Rogue|Evil|Elf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Elv+E+Rogue+Half.png",
  "Character|Rogue|Evil|Free Kingdoms": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Freek+E+Rogue+Half.png",
  "Character|Rogue|Evil|Mercenary": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Merc+E+Rogue+Half.png",
  "Character|Rogue|Evil|Nothrog": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Ntg+E+Rogue+Half.png",
  "Character|Rogue|Evil|The Chosen": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Cho+E+Rogue.png",
  "Character|Rogue|Good|Deverenian": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dev+G+Rogue+Half.png",
  "Character|Rogue|Good|Dwarf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dw+G+Rogue+Half.png",
  "Character|Rogue|Good|Elf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Elv+G+Rogue+Half.png",
  "Character|Rogue|Good|Free Kingdoms": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Freek+G+Rogue+Half.png",
  "Character|Rogue|Good|Mercenary": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Merc+G+Rogue+Half.png",
  "Character|Rogue|Good|Nothrog": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Ntg+G+Rogue+Half.png",
  "Character|Rogue|Good|The Chosen": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Cho+G+Rogue.png",
  "Character|Wizard|Evil|Deverenian": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dev+E+Wiz+Half.png",
  "Character|Wizard|Evil|Dwarf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dw+E+Wiz+Half.png",
  "Character|Wizard|Evil|Elf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Elv+E+Wiz+Half.png",
  "Character|Wizard|Evil|Free Kingdoms": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Freek+E+Wiz+Half.png",
  "Character|Wizard|Evil|Mercenary": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Merc+E+Wiz+Half.png",
  "Character|Wizard|Evil|Nothrog": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Ntg+E+Wiz+Half.png",
  "Character|Wizard|Evil|The Chosen": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Cho+E+Wiz.png",
  "Character|Wizard|Good|Deverenian": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dev+G+Wiz+Half.png",
  "Character|Wizard|Good|Dwarf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Dw+G+Wiz+Half.png",
  "Character|Wizard|Good|Elf": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Elv+G+Wiz+Half.png",
  "Character|Wizard|Good|Free Kingdoms": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Freek+G+Wiz+Half.png",
  "Character|Wizard|Good|Mercenary": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Merc+G+Wiz+Half.png",
  "Character|Wizard|Good|Nothrog": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Ntg+G+Wiz+Half.png",
  "Character|Wizard|Good|The Chosen": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Cho+G+Wiz.png",
  "Item|Classless": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Item+Classless.png",
  "Item|Cleric": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Item+Cleric.png",
  "Item|Fighter": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Item+Fighter.png",
  "Item|Rogue": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Item+Rogue.png",
  "Item|Wizard": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/Item+Wizard.png",
  "no_template": "https://images.theaccordlands.com/file/WarlordCards/Warlord+Card+Images/Templates/No_Template.png"
}