export default {
    "Character|Classless|Evil|Deverenian": "/images/Dev E Class Half.png",
    "Character|Classless|Evil|Dwarf": "/images/Dw E Class Half.png",
    "Character|Classless|Evil|Elf": "/images/Elv E Class Half.png",
    "Character|Classless|Evil|Free Kingdoms": "/images/Freek E Class Half.png",
    "Character|Classless|Evil|Mercenary": "/images/Merc E Class Half.png",
    "Character|Classless|Evil|Nothrog": "/images/Ntg E Class Half.png",
    "Character|Classless|Evil|The Chosen": "/images/Cho E Class.png",
    "Character|Classless|Good|Deverenian": "/images/Dev G Class Half.png",
    "Character|Classless|Good|Dwarf": "/images/Dw G Class Half.png",
    "Character|Classless|Good|Elf": "/images/Elv G Class Half.png",
    "Character|Classless|Good|Free Kingdoms": "/images/Freek G Class Half.png",
    "Character|Classless|Good|Mercenary": "/images/Merc G Class Half.png",
    "Character|Classless|Good|Nothrog": "/images/Ntg G Class Half.png",
    "Character|Classless|Good|The Chosen": "/images/Cho G Class.png",
    "Character|Cleric|Evil|Deverenian": "/images/Dev E Cleric Half.png",
    "Character|Cleric|Evil|Dwarf": "/images/Dw E Cleric Half.png",
    "Character|Cleric|Evil|Elf": "/images/Elv E Cleric Half.png",
    "Character|Cleric|Evil|Free Kingdoms": "/images/Freek E Cleric Half.png",
    "Character|Cleric|Evil|Mercenary": "/images/Merc E Cleric Half.png",
    "Character|Cleric|Evil|Nothrog": "/images/Ntg E Cleric Half.png",
    "Character|Cleric|Evil|The Chosen": "/images/Cho E Cleric.png",
    "Character|Cleric|Good|Deverenian": "/images/Dev G Cleric Half.png",
    "Character|Cleric|Good|Dwarf": "/images/Dw G Cleric Half.png",
    "Character|Cleric|Good|Elf": "/images/Elv G Cleric Half.png",
    "Character|Cleric|Good|Free Kingdoms": "/images/Freek G Cleric Half.png",
    "Character|Cleric|Good|Mercenary": "/images/Merc G Cleric Half.png",
    "Character|Cleric|Good|Nothrog": "/images/Ntg G Cleric Half.png",
    "Character|Cleric|Good|The Chosen": "/images/Cho G Cleric.png",
    "Character|Fighter|Evil|Deverenian": "/images/Dev E Fight Half.png",
    "Character|Fighter|Evil|Dwarf": "/images/Dw E Fight Half.png",
    "Character|Fighter|Evil|Elf": "/images/Elv E Fight Half.png",
    "Character|Fighter|Evil|Free Kingdoms": "/images/Freek E Fight Half.png",
    "Character|Fighter|Evil|Mercenary": "/images/Merc E Fight Half.png",
    "Character|Fighter|Evil|Nothrog": "/images/Ntg E Fight Half.png",
    "Character|Fighter|Evil|The Chosen": "/images/Cho E Fight.png",
    "Character|Fighter|Good|Deverenian": "/images/Dev G Fight Half.png",
    "Character|Fighter|Good|Dwarf": "/images/Dw G Fight Half.png",
    "Character|Fighter|Good|Elf": "/images/Elv G Fight Half.png",
    "Character|Fighter|Good|Free Kingdoms": "/images/Freek G Fight Half.png",
    "Character|Fighter|Good|Mercenary": "/images/Merc G Fight Half.png",
    "Character|Fighter|Good|Nothrog": "/images/Ntg G Fight Half.png",
    "Character|Fighter|Good|The Chosen": "/images/Cho G Fight.png",
    "Character|Rogue|Evil|Deverenian": "/images/Dev E Rogue Half.png",
    "Character|Rogue|Evil|Dwarf": "/images/Dw E Rogue Half.png",
    "Character|Rogue|Evil|Elf": "/images/Elv E Rogue Half.png",
    "Character|Rogue|Evil|Free Kingdoms": "/images/Freek E Rogue Half.png",
    "Character|Rogue|Evil|Mercenary": "/images/Merc E Rogue Half.png",
    "Character|Rogue|Evil|Nothrog": "/images/Ntg E Rogue Half.png",
    "Character|Rogue|Evil|The Chosen": "/images/Cho E Rogue.png",
    "Character|Rogue|Good|Deverenian": "/images/Dev G Rogue Half.png",
    "Character|Rogue|Good|Dwarf": "/images/Dw G Rogue Half.png",
    "Character|Rogue|Good|Elf": "/images/Elv G Rogue Half.png",
    "Character|Rogue|Good|Free Kingdoms": "/images/Freek G Rogue Half.png",
    "Character|Rogue|Good|Mercenary": "/images/Merc G Rogue Half.png",
    "Character|Rogue|Good|Nothrog": "/images/Ntg G Rogue Half.png",
    "Character|Rogue|Good|The Chosen": "/images/Cho G Rogue.png",
    "Character|Wizard|Evil|Deverenian": "/images/Dev E Wiz Half.png",
    "Character|Wizard|Evil|Dwarf": "/images/Dw E Wiz Half.png",
    "Character|Wizard|Evil|Elf": "/images/Elv E Wiz Half.png",
    "Character|Wizard|Evil|Free Kingdoms": "/images/Freek E Wiz Half.png",
    "Character|Wizard|Evil|Mercenary": "/images/Merc E Wiz Half.png",
    "Character|Wizard|Evil|Nothrog": "/images/Ntg E Wiz Half.png",
    "Character|Wizard|Evil|The Chosen": "/images/Cho E Wiz.png",
    "Character|Wizard|Good|Deverenian": "/images/Dev G Wiz Half.png",
    "Character|Wizard|Good|Dwarf": "/images/Dw G Wiz Half.png",
    "Character|Wizard|Good|Elf": "/images/Elv G Wiz Half.png",
    "Character|Wizard|Good|Free Kingdoms": "/images/Freek G Wiz Half.png",
    "Character|Wizard|Good|Mercenary": "/images/Merc G Wiz Half.png",
    "Character|Wizard|Good|Nothrog": "/images/Ntg G Wiz Half.png",
    "Character|Wizard|Good|The Chosen": "/images/Cho G Wiz.png"
}