export default {
    "Character|Classless|Evil|Deverenian": "/images/test/Dev E Class Half.png",
    "Character|Classless|Evil|Dwarf": "/images/test/Dw E Class Half.png",
    "Character|Classless|Evil|Elf": "/images/test/Elv E Class Half.png",
    "Character|Classless|Evil|Free Kingdoms": "/images/test/Freek E Class Half.png",
    "Character|Classless|Evil|Mercenary": "/images/test/Merc E Class Half.png",
    "Character|Classless|Evil|Nothrog": "/images/test/Ntg E Class Half.png",
    "Character|Classless|Evil|The Chosen": "/images/test/Cho E Class.png",
    "Character|Classless|Good|Deverenian": "/images/test/Dev G Class Half.png",
    "Character|Classless|Good|Dwarf": "/images/test/Dw G Class Half.png",
    "Character|Classless|Good|Elf": "/images/test/Elv G Class Half.png",
    "Character|Classless|Good|Free Kingdoms": "/images/test/Freek G Class Half.png",
    "Character|Classless|Good|Mercenary": "/images/test/Merc G Class Half.png",
    "Character|Classless|Good|Nothrog": "/images/test/Ntg G Class Half.png",
    "Character|Classless|Good|The Chosen": "/images/test/Cho G Class.png",
    "Character|Cleric|Evil|Deverenian": "/images/test/Dev E Cleric Half.png",
    "Character|Cleric|Evil|Dwarf": "/images/test/Dw E Cleric Half.png",
    "Character|Cleric|Evil|Elf": "/images/test/Elv E Cleric Half.png",
    "Character|Cleric|Evil|Free Kingdoms": "/images/test/Freek E Cleric Half.png",
    "Character|Cleric|Evil|Mercenary": "/images/test/Merc E Cleric Half.png",
    "Character|Cleric|Evil|Nothrog": "/images/test/Ntg E Cleric Half.png",
    "Character|Cleric|Evil|The Chosen": "/images/test/Cho E Cleric.png",
    "Character|Cleric|Good|Deverenian": "/images/test/Dev G Cleric Half.png",
    "Character|Cleric|Good|Dwarf": "/images/test/Dw G Cleric Half.png",
    "Character|Cleric|Good|Elf": "/images/test/Elv G Cleric Half.png",
    "Character|Cleric|Good|Free Kingdoms": "/images/test/Freek G Cleric Half.png",
    "Character|Cleric|Good|Mercenary": "/images/test/Merc G Cleric Half.png",
    "Character|Cleric|Good|Nothrog": "/images/test/Ntg G Cleric Half.png",
    "Character|Cleric|Good|The Chosen": "/images/test/Cho G Cleric.png",
    "Character|Fighter|Evil|Deverenian": "/images/test/Dev E Fight Half.png",
    "Character|Fighter|Evil|Dwarf": "/images/test/Dw E Fight Half.png",
    "Character|Fighter|Evil|Elf": "/images/test/Elv E Fight Half.png",
    "Character|Fighter|Evil|Free Kingdoms": "/images/test/Freek E Fight Half.png",
    "Character|Fighter|Evil|Mercenary": "/images/test/Merc E Fight Half.png",
    "Character|Fighter|Evil|Nothrog": "/images/test/Ntg E Fight Half.png",
    "Character|Fighter|Evil|The Chosen": "/images/test/Cho E Fight.png",
    "Character|Fighter|Good|Deverenian": "/images/test/Dev G Fight Half.png",
    "Character|Fighter|Good|Dwarf": "/images/test/Dw G Fight Half.png",
    "Character|Fighter|Good|Elf": "/images/test/Elv G Fight Half.png",
    "Character|Fighter|Good|Free Kingdoms": "/images/test/Freek G Fight Half.png",
    "Character|Fighter|Good|Mercenary": "/images/test/Merc G Fight Half.png",
    "Character|Fighter|Good|Nothrog": "/images/test/Ntg G Fight Half.png",
    "Character|Fighter|Good|The Chosen": "/images/test/Cho G Fight.png",
    "Character|Rogue|Evil|Deverenian": "/images/test/Dev E Rogue Half.png",
    "Character|Rogue|Evil|Dwarf": "/images/test/Dw E Rogue Half.png",
    "Character|Rogue|Evil|Elf": "/images/test/Elv E Rogue Half.png",
    "Character|Rogue|Evil|Free Kingdoms": "/images/test/Freek E Rogue Half.png",
    "Character|Rogue|Evil|Mercenary": "/images/test/Merc E Rogue Half.png",
    "Character|Rogue|Evil|Nothrog": "/images/test/Ntg E Rogue Half.png",
    "Character|Rogue|Evil|The Chosen": "/images/test/Cho E Rogue.png",
    "Character|Rogue|Good|Deverenian": "/images/test/Dev G Rogue Half.png",
    "Character|Rogue|Good|Dwarf": "/images/test/Dw G Rogue Half.png",
    "Character|Rogue|Good|Elf": "/images/test/Elv G Rogue Half.png",
    "Character|Rogue|Good|Free Kingdoms": "/images/test/Freek G Rogue Half.png",
    "Character|Rogue|Good|Mercenary": "/images/test/Merc G Rogue Half.png",
    "Character|Rogue|Good|Nothrog": "/images/test/Ntg G Rogue Half.png",
    "Character|Rogue|Good|The Chosen": "/images/test/Cho G Rogue.png",
    "Character|Wizard|Evil|Deverenian": "/images/test/Dev E Wiz Half.png",
    "Character|Wizard|Evil|Dwarf": "/images/test/Dw E Wiz Half.png",
    "Character|Wizard|Evil|Elf": "/images/test/Elv E Wiz Half.png",
    "Character|Wizard|Evil|Free Kingdoms": "/images/test/Freek E Wiz Half.png",
    "Character|Wizard|Evil|Mercenary": "/images/test/Merc E Wiz Half.png",
    "Character|Wizard|Evil|Nothrog": "/images/test/Ntg E Wiz Half.png",
    "Character|Wizard|Evil|The Chosen": "/images/test/Cho E Wiz.png",
    "Character|Wizard|Good|Deverenian": "/images/test/Dev G Wiz Half.png",
    "Character|Wizard|Good|Dwarf": "/images/test/Dw G Wiz Half.png",
    "Character|Wizard|Good|Elf": "/images/test/Elv G Wiz Half.png",
    "Character|Wizard|Good|Free Kingdoms": "/images/test/Freek G Wiz Half.png",
    "Character|Wizard|Good|Mercenary": "/images/test/Merc G Wiz Half.png",
    "Character|Wizard|Good|Nothrog": "/images/test/Ntg G Wiz Half.png",
    "Character|Wizard|Good|The Chosen": "/images/test/Cho G Wiz.png"
}