export default {
    "Character|Classless|Evil|Deverenian": "https:drive.google.com/uc?export=view&id=1w92lEQobIu6g9x_45UGL8lo7Wgfod2QK",
    "Character|Classless|Evil|Dwarf": "https:drive.google.com/uc?export=view&id=17FKleyNyaYeKwFVV4aA7xo81PjehXXCl",
    "Character|Classless|Evil|Elf": "https:drive.google.com/uc?export=view&id=11R3xcjBuUn7lPPJWsHi8ZOLA4q32irxZ",
    "Character|Classless|Evil|Free Kingdoms": "https:drive.google.com/uc?export=view&id=1a7OuGh5_ja0F91T3YXJ8ITwKGrLK6DFG",
    "Character|Classless|Evil|Mercenary": "https:drive.google.com/uc?export=view&id=1itOop-i9gEu0RPdyiDm5Y8GXCpdWFJ_q",
    "Character|Classless|Evil|Nothrog": "https:drive.google.com/uc?export=view&id=1PwvVYC3gPppwsUtVghM5nux2lzZttagV",
    "Character|Classless|Evil|The Chosen": "https:drive.google.com/uc?export=view&id=183frgPSB5UhTTYVbu_woA1Va8ZJsmLTw",
    "Character|Classless|Good|Deverenian": "https:drive.google.com/uc?export=view&id=115i71o3NlAiSpwbCAFXN_xJpiXH4IZ3-",
    "Character|Classless|Good|Dwarf": "https:drive.google.com/uc?export=view&id=1D7C4bxFoLANSYIXdwcSEl-Q5_N2J40YZ",
    "Character|Classless|Good|Elf": "https:drive.google.com/uc?export=view&id=1Ab1vPNB2WDFjHrwOwUwfqE558pABkfmM",
    "Character|Classless|Good|Free Kingdoms": "https:drive.google.com/uc?export=view&id=1UVXQO17xKQkEnx1lBP6CCspw6_5NqeEj",
    "Character|Classless|Good|Mercenary": "https:drive.google.com/uc?export=view&id=1nxiFupFKerp6TA52D0lYBwpFtoFcMYXD",
    "Character|Classless|Good|Nothrog": "https:drive.google.com/uc?export=view&id=1VlABgZA1cOuMeB7yFFJVe6qp4MeDc82N",
    "Character|Classless|Good|The Chosen": "https:drive.google.com/uc?export=view&id=1eIfjJj-0D6twU5ST5snwY7Awa4O00chS",
    "Character|Cleric|Evil|Deverenian": "https:drive.google.com/uc?export=view&id=1iiGk_Mtcj_igxIakga4d9swHjALn6Rsn",
    "Character|Cleric|Evil|Dwarf": "https:drive.google.com/uc?export=view&id=1-xYPEcs9p8IY91ox4LYthFrH_5qlYK3_",
    "Character|Cleric|Evil|Elf": "https:drive.google.com/uc?export=view&id=1tP-iYvxGEJUwXZ7JHxbPuh6rhjQBcnJG",
    "Character|Cleric|Evil|Free Kingdoms": "https:drive.google.com/uc?export=view&id=1w4_vgQdFjlwQMlNpjeL_L4q0-Nfolrng",
    "Character|Cleric|Evil|Mercenary": "https:drive.google.com/uc?export=view&id=1uwJsOBqVtxlp-VoPSMw-tJDZE_EN6WZM",
    "Character|Cleric|Evil|Nothrog": "https:drive.google.com/uc?export=view&id=14mNcXvTDaFngVBDcwiaYXVV88wxja4Xc",
    "Character|Cleric|Evil|The Chosen": "https:drive.google.com/uc?export=view&id=1LuSTMcAW27hTmGuBzLDhvBfYY7q6FA87",
    "Character|Cleric|Good|Deverenian": "https:drive.google.com/uc?export=view&id=1K7terOMtVvbMPBeS5eUbAjGd-SScyAK4",
    "Character|Cleric|Good|Dwarf": "https:drive.google.com/uc?export=view&id=1PSD_gwl-6bqNGOpum1_Ktuif6SNMJdnN",
    "Character|Cleric|Good|Elf": "https:drive.google.com/uc?export=view&id=1y4xR-1WfQ1IbYNksd02u8i6PqpPRAs0A",
    "Character|Cleric|Good|Free Kingdoms": "https:drive.google.com/uc?export=view&id=1rw1w22xCslh8aE2dVd3pKfoS7wsiwbm0",
    "Character|Cleric|Good|Mercenary": "https:drive.google.com/uc?export=view&id=1QADQjDQAhVFp3iklC1Ac3ivajexq1GIc",
    "Character|Cleric|Good|Nothrog": "https:drive.google.com/uc?export=view&id=1LTnR89j1cWdLSc5iowyWDEmYSGY_NYoP",
    "Character|Cleric|Good|The Chosen": "https:drive.google.com/uc?export=view&id=18jQDXRB1kg-lS8PZUtn4X6LCHZrfQXgg",
    "Character|Fighter|Evil|Deverenian": "https:drive.google.com/uc?export=view&id=1mdXQizXbIWke_QLIYgRWsQMQmVIB_1p5",
    "Character|Fighter|Evil|Dwarf": "https:drive.google.com/uc?export=view&id=1vlV28WLU-_ZXCDjVKB8BcavqCpAoimSo",
    "Character|Fighter|Evil|Elf": "https:drive.google.com/uc?export=view&id=1X53PpZdtwig7UDUoEzZUV6TEZJXA8qXu",
    "Character|Fighter|Evil|Free Kingdoms": "https:drive.google.com/uc?export=view&id=1bhN8rAEmXpLww7_u0erU9FD2lLqvRfth",
    "Character|Fighter|Evil|Mercenary": "https:drive.google.com/uc?export=view&id=1rTBZl5kwh203NbdKtdn6DkFIyqY2AUUG",
    "Character|Fighter|Evil|Nothrog": "https:drive.google.com/uc?export=view&id=1BsBLu3v1ReVw5jcUOkqAakTIjkO53xse",
    "Character|Fighter|Evil|The Chosen": "https:drive.google.com/uc?export=view&id=1KryfTW9JDpOXio2HTFTL0mz8kfpWeh2D",
    "Character|Fighter|Good|Deverenian": "https:drive.google.com/uc?export=view&id=1L68dGqoDkDEjLlCxxo-14aX15R4xxvHl",
    "Character|Fighter|Good|Dwarf": "https:drive.google.com/uc?export=view&id=1OM3RHyrXSneeeJCsBdhOzrspYWfsf0Pu",
    "Character|Fighter|Good|Elf": "https:drive.google.com/uc?export=view&id=1FWqyGn9qDPLjjspwEnisDM1ePORC4Z1M",
    "Character|Fighter|Good|Free Kingdoms": "https:drive.google.com/uc?export=view&id=1GgilRmw5f0JN6sHBfG4MrSINIDajHp9-",
    "Character|Fighter|Good|Mercenary": "https:drive.google.com/uc?export=view&id=1AwvgeqzKK6---X9Vl6Ciru6kz1be359-",
    "Character|Fighter|Good|Nothrog": "https:drive.google.com/uc?export=view&id=1kEvP0zv_Dl3j5_1gAN7L1AxTpUsmNiTP",
    "Character|Fighter|Good|The Chosen": "https:drive.google.com/uc?export=view&id=1SkhShkIt4ll63cWFchPihw8sIx3RgILO",
    "Character|Rogue|Evil|Deverenian": "https:drive.google.com/uc?export=view&id=1VDwv4TGMPlpCVZsK8HEYIFetCdrrQwS8",
    "Character|Rogue|Evil|Dwarf": "https:drive.google.com/uc?export=view&id=1JkvVWu5yYjBWxSq32IvYP8CiFKiGK24Z",
    "Character|Rogue|Evil|Elf": "https:drive.google.com/uc?export=view&id=1oiJC90LRiC4nBrumrEvOgXxZFQNVnkeX",
    "Character|Rogue|Evil|Free Kingdoms": "https:drive.google.com/uc?export=view&id=17oPG--Cr57R9qyC40zZg5xcWDoZdXsJC",
    "Character|Rogue|Evil|Mercenary": "https:drive.google.com/uc?export=view&id=1CdTlX53_Z0CF_bpwIqixjpDE94nDUhUb",
    "Character|Rogue|Evil|Nothrog": "https:drive.google.com/uc?export=view&id=1xoyFg9G145lf1Ad1b_jPfWu1wXya514_",
    "Character|Rogue|Evil|The Chosen": "https:drive.google.com/uc?export=view&id=1kkdilQZhP8EzK19dNtzRA7RKm0BTE4Br",
    "Character|Rogue|Good|Deverenian": "https:drive.google.com/uc?export=view&id=1wThRSg9X2p4OyuhTHOsO5TbpDs2du5QQ",
    "Character|Rogue|Good|Dwarf": "https:drive.google.com/uc?export=view&id=19quefPvw0R53x4974VjWLkJs1umySUC4",
    "Character|Rogue|Good|Elf": "https:drive.google.com/uc?export=view&id=1Mtw4dM6BhskOgMIESvPrfORvStaHtlPp",
    "Character|Rogue|Good|Free Kingdoms": "https:drive.google.com/uc?export=view&id=1X7S8nQDYDi0RYZVNRSBPTtaPWmiN7KoY",
    "Character|Rogue|Good|Mercenary": "https:drive.google.com/uc?export=view&id=1f8n2CjmX7R1EjMiE7iVPi-zJQmZ6lFCM",
    "Character|Rogue|Good|Nothrog": "https:drive.google.com/uc?export=view&id=1cSA77c6Ju9SOWjLnoM4oJ6eHKHutZmhI",
    "Character|Rogue|Good|The Chosen": "https:drive.google.com/uc?export=view&id=14Gt1gzeX8aEQTJJOFJFZ5MFBFUWFOKZL",
    "Character|Wizard|Evil|Deverenian": "https:drive.google.com/uc?export=view&id=1_OjfGMIMdVgknQHyinXvxI8h1ncElfnx",
    "Character|Wizard|Evil|Dwarf": "https:drive.google.com/uc?export=view&id=1jfeBlTJ-4mlulx8Z2pTKtLsJda9-kyjc",
    "Character|Wizard|Evil|Elf": "https:drive.google.com/uc?export=view&id=16wv-cSSg20B-WXzBvFlXSNu0vdRbll7Y",
    "Character|Wizard|Evil|Free Kingdoms": "https:drive.google.com/uc?export=view&id=1yZWShxpBC4vu7AOE2_Td_sO2SSwSLC-i",
    "Character|Wizard|Evil|Mercenary": "https:drive.google.com/uc?export=view&id=17NYEz-gpeGk9pBXYiKLTGX3dzP9csK2t",
    "Character|Wizard|Evil|Nothrog": "https:drive.google.com/uc?export=view&id=17OrmMhUlliWPRLwy8bXRYusJidKTqg0p",
    "Character|Wizard|Evil|The Chosen": "https:drive.google.com/uc?export=view&id=1jifSIfUyubxnnd-z-2SyAKsKBPTn3UXs",
    "Character|Wizard|Good|Deverenian": "https:drive.google.com/uc?export=view&id=15ZIhcGESio-28V8Plg0mZmaKYkfFBzJX",
    "Character|Wizard|Good|Dwarf": "https:drive.google.com/uc?export=view&id=1_u_i7dnUoWiFRnZAJPebmY95uLDVd5X4",
    "Character|Wizard|Good|Elf": "https:drive.google.com/uc?export=view&id=1b3PLBj8mdVcMByYrCw1CF-JltRiKxOPM",
    "Character|Wizard|Good|Free Kingdoms": "https:drive.google.com/uc?export=view&id=1neNK4kExrwPn7ZjxoD_WT3kYkaYyGhi2",
    "Character|Wizard|Good|Mercenary": "https:drive.google.com/uc?export=view&id=1mDl69auRGtXpUG0gE7ZWQkBDpalu7Zfb",
    "Character|Wizard|Good|Nothrog": "https:drive.google.com/uc?export=view&id=12ns7HbLl3u8Blq7fdq3KitzAlJphtw7-",
    "Character|Wizard|Good|The Chosen": "https:drive.google.com/uc?export=view&id=1hDgwG6-GKcw2cRSxHzfTd9m0EdMpmr6_",
    "no_template": "/images/test/no_template.png"
}