import { describe, it, expect } from 'vitest'
import rulesets from '../../src/scripts/rulesets/cardRules'

const byName = (name) => rulesets.find(r => r.description === name).ruleset
const base = byName('No Ruleset')

// Reference lists are normally generated by prebuild.js from cards.json.
const refs = {
  typeList: ['Character', 'Action', 'Item', 'Epic Class', 'Battlefield', 'Dungeon'],
  subtypeLists: { Character: ['Warlord', 'Overlord'] },
  alignmentList: ['Good', 'Evil', 'Neutral'],
  classList: ['Fighter', 'Wizard', 'Classless'],
  factionList: ['Nothrog Legions', 'Elven Branches'],
  damageTypeList: ['Physical', 'Magical'],
  traitList: ['Undead'],
  keywordList: [{ name: 'Epic', hasValue: false }],
  featList: ['Cleave'],
  editionList: ['Alliance'],
  setList: ['Siege (SG)'],
  rarityList: ['Common']
}

const validate = (ruleset, prop, val, cardData = {}) =>
  ruleset[prop] && ruleset[prop].validate
    ? ruleset[prop].validate(val, cardData, refs)
    : undefined

describe('ruleset registry', () => {
  it('exposes the four expected rulesets in order', () => {
    expect(rulesets.map(r => r.description)).toEqual([
      'No Ruleset', 'Tournament 1.0', 'Tournament 1.1', 'Tournament 2.0'
    ])
  })

  it('is deeply frozen so rulesets cannot be mutated at runtime', () => {
    expect(Object.isFrozen(rulesets)).toBe(true)
    expect(Object.isFrozen(base)).toBe(true)
    expect(Object.isFrozen(base.name)).toBe(true)
  })

  it('exposes the shared additional keywords on every ruleset', () => {
    for (const { ruleset } of rulesets) {
      expect(ruleset.general.additionalKeywords).toContain('Limited Order:')
    }
  })
})

describe('base validation: name', () => {
  it('requires a name', () => {
    expect(validate(base, 'name', null)).toMatch(/name is required/i)
  })

  it('accepts a name', () => {
    expect(validate(base, 'name', 'Orc')).toBeUndefined()
  })
})

describe('base validation: type', () => {
  it('requires a type', () => {
    expect(validate(base, 'type', null)).toMatch(/type is required/i)
  })

  it('rejects a type not in the reference list', () => {
    expect(validate(base, 'type', 'Spaceship')).toMatch(/not a valid type/i)
  })

  it('accepts a known type', () => {
    expect(validate(base, 'type', 'Character')).toBeUndefined()
  })
})

describe('base validation: subtype', () => {
  it('rejects a subtype that does not belong to the card type', () => {
    expect(validate(base, 'subtype', ['Wizard'], { type: 'Character' }))
      .toMatch(/not a valid Character subtype/i)
  })

  it('accepts a valid subtype for the type', () => {
    expect(validate(base, 'subtype', ['Warlord'], { type: 'Character' })).toBeUndefined()
  })

  it('accepts an absent subtype', () => {
    expect(validate(base, 'subtype', null, { type: 'Character' })).toBeUndefined()
  })
})

describe('base validation: alignment', () => {
  it('requires alignment for Characters', () => {
    expect(validate(base, 'alignment', null, { type: 'Character' }))
      .toMatch(/required for this card type/i)
  })

  it('forbids alignment on Items', () => {
    expect(validate(base, 'alignment', 'Good', { type: 'Item' }))
      .toMatch(/invalid for this card type/i)
  })

  it('accepts a valid alignment on a Character', () => {
    expect(validate(base, 'alignment', 'Good', { type: 'Character' })).toBeUndefined()
  })

  it('rejects an unknown alignment', () => {
    expect(validate(base, 'alignment', 'Chaotic Fuchsia', { type: 'Character' }))
      .toMatch(/not a valid alignment/i)
  })
})

describe('base validation: text multiclass rule', () => {
  const multi = { type: 'Character', class: ['Fighter', 'Wizard'] }

  it('requires multiclass to be stated in the card text', () => {
    expect(validate(base, 'text', 'Some unrelated text.', multi))
      .toMatch(/multiclass must be specified/i)
  })

  it('accepts text that states the multiclass', () => {
    expect(validate(base, 'text', 'This character is a Wizard.', multi)).toBeUndefined()
  })

  it('does not apply to single-class characters', () => {
    expect(validate(base, 'text', 'Anything', { type: 'Character', class: ['Fighter'] }))
      .toBeUndefined()
  })
})

describe('tournament rulesets', () => {
  const tournaments = ['Tournament 1.0', 'Tournament 1.1', 'Tournament 2.0']

  it.each(tournaments)('%s still enforces the base name rule', (name) => {
    // Proves setFallback chained the base validator behind the tournament one.
    expect(validate(byName(name), 'name', null)).toMatch(/name is required/i)
  })

  it.each(tournaments)('%s exposes point computation', (name) => {
    const ruleset = byName(name)
    const withPoints = Object.keys(ruleset).filter(p => ruleset[p] && ruleset[p].computePoints)
    expect(withPoints.length).toBeGreaterThan(0)
  })

  it('No Ruleset has no point computation', () => {
    const withPoints = Object.keys(base).filter(p => base[p] && base[p].computePoints)
    expect(withPoints).toEqual([])
  })
})

describe('computePoints is total over valid cards', () => {
  // Guards the Vue 3 migration: point costing must not start throwing on
  // ordinary cards. Exercises every property that defines computePoints.
  const card = {
    name: 'Test Character',
    type: 'Character',
    alignment: 'Good',
    class: ['Fighter'],
    faction: ['Nothrog Legions'],
    level: 3,
    attack: [3],
    armorClass: 4,
    skill: 2,
    hitPoints: 10,
    traits: ['Undead'],
    keywords: [],
    feats: [],
    text: '',
    printInfos: []
  }

  for (const name of ['Tournament 1.0', 'Tournament 1.1', 'Tournament 2.0']) {
    it(`${name} computes points without throwing`, () => {
      const ruleset = byName(name)
      for (const prop of Object.keys(ruleset)) {
        const config = ruleset[prop]
        if (!config || !config.computePoints) continue
        expect(() => config.computePoints(card[prop], card, refs)).not.toThrow()
      }
    })

    it(`${name} tolerates a sparse card`, () => {
      const ruleset = byName(name)
      const sparse = { name: 'X', type: 'Character' }
      for (const prop of Object.keys(ruleset)) {
        const config = ruleset[prop]
        if (!config || !config.computePoints) continue
        expect(() => config.computePoints(sparse[prop], sparse, refs)).not.toThrow()
      }
    })
  }
})

describe('validators are total', () => {
  // Every validator must tolerate null/sparse input without throwing.
  it.each(rulesets.map(r => r.description))('%s validators survive a sparse card', (name) => {
    const ruleset = byName(name)
    const sparse = {}
    for (const prop of Object.keys(ruleset)) {
      const config = ruleset[prop]
      if (!config || !config.validate) continue
      expect(() => config.validate(undefined, sparse, refs)).not.toThrow()
    }
  })
})
