import { mount } from '@vue/test-utils'
import store from '../../src/store'
import { createBootstrap } from 'bootstrap-vue-next'

// Shared setup for the component suites. These mount real components against a
// real Vuex store, because the bugs worth catching here live in the wiring (a
// handler that never fires, a value that never reaches the model) and a stubbed
// store would hide exactly that.

// Reference lists are generated by prebuild.js from cards.json. This is a
// hand-written stand-in, wide enough to exercise multi-value fields, because
// the visual fixture only carries one subtype and one feat.
export const referenceLists = {
  typeList: ['Character', 'Action', 'Item', 'Epic Class', 'Battlefield', 'Dungeon'],
  subtypeLists: {
    Character: ['Warlord', 'Overlord', 'Dragon Lord', 'Medusan Lord', 'Daemonlord']
  },
  alignmentList: ['Good', 'Evil', 'Neutral'],
  classList: ['Classless', 'Cleric', 'Fighter', 'Rogue', 'Wizard'],
  factionList: ['Deverenian Empire', 'Elven Branches', 'Mercenary Guilds', 'Nothrog Legions'],
  damageTypeList: ['Physical', 'Magical'],
  traitList: ['Abyssal', 'Aquatic', 'Dragon', 'Undead'],
  keywordList: [
    { name: 'Challenge Rating', hasValue: true },
    { name: 'Charges', hasValue: true },
    { name: 'Cursed', hasValue: false },
    { name: 'True Strike', hasValue: false }
  ],
  featList: ['Charisma', 'Defend', 'Magic Resistance', 'Stealth'],
  editionList: ['4th Edition', 'Alliance', 'Ancients'],
  setList: ['Siege (SG)', 'Core (CR)'],
  rarityList: ['Common', 'Fixed', 'Promo']
}

// The real store, seeded. A stand-in would drift from the thing the components
// actually talk to, and the store already has its own suite.
export const makeStore = (state = {}) => {
  Object.assign(store.state, {
    cardsLoaded: true,
    referenceLists,
    viewPortWidth: 1280,
    ...state
  })
  return store
}

export const mountComponent = (component, { store, props, stubs, ...rest } = {}) =>
  mount(component, {
    props,
    global: {
      plugins: [store || makeStore(), createBootstrap()],
      stubs: {
        // Router links and the page chrome are not what these suites are
        // about, and mounting them drags in the whole app.
        RouterLink: true,
        'router-link': true,
        HeaderFooter: { template: '<div><slot/></div>' },
        CardImageCreator: true,
        ...stubs
      }
    },
    ...rest
  })

// localStorage is a real dependency of the builder and the editor: the card is
// saved on every edit and restored on mount. jsdom provides one, but it
// persists between tests in the same file.
export const clearStorage = () => {
  localStorage.clear()
}

/**
 * The builder saves on a 1000ms debounce and refreshes its cache on nextTick.
 * Rather than sleep, drive the component's own methods and await them.
 */
export const settle = async (w, ticks = 3) => {
  for (let i = 0; i < ticks; i++) await w.vm.$nextTick()
}
